#!/bin/bash

mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-e5df49a4.efs.ap-southeast-1.amazonaws.com:/  /var/lib/jenkins

mount /dev/xvda2 /var/lib/jenkins/plugins

chown -R jenkins /var/lib/jenkins/

systemctl start jenkins


